### ISSUE TITLE
Move launch.openshift.io hosting to DevTools OSD

### ISSUE THREAD

**Issue by ALRubinger** [openshiftio/appdev-planning#37]
Upstream tracking ticket for moving our infrastructure.

RHT Internal Reference: https://issues.jboss.org/projects/OBST/issues/OBST-264

**Comment by gastaldi** [comment]
According to @vpavlin, these are the things we need to do:

* Get the prod configmaps, secrets and routes to saas-crypt repo we manage 
* Create projects in rh-idev and dsaas
* Start deploying to the project in rh-idev from CI
* Create configuration for openshiftio/saas for the "promote to prod" step
* Configure the promote job to be able to deploy to the dsaas project

**Comment by gastaldi** [comment]
@vpavlin @kbsingh what do we need to do to get this started?

**Comment by kbsingh** [comment]
I believe this is underway already

**Comment by gastaldi** [comment]
Thank you @kbsingh. Are you the one working on this?

**Comment by gastaldi** [comment]
Can someone provide me an update of this ongoing activity?

**Comment by kbsingh** [comment]
@gastaldi we have this in our present sprint to help you guys over the process. @vpavlin is the one running the work itself and will update the thread once he has something tangiable. There is a fair bit of moving around that needs to happen in the infra and the infra pipelines before we can slot you in. Most of the time's been spent on that so far. I'll let @vpavlin drop in details once its there.

**Comment by gastaldi** [comment]
Thanks @kbsingh and @vpavlin.

**Comment by vpavlin** [comment]
Sorry guys, I completely missed the thread. I am reworking structure of our prod deployment tracking repository at the moment to make it easier to add you to the mix. I hope to have it ready tomorrow, so that we can start moving with other bits.

**Comment by vpavlin** [comment]
@gastaldi Can you give me list of repos containing templates we need to run? And also share any prod/stage secrets/configMaps we need to import to prod/stage clusters (I guess at least secrets should be shared privately:) )?

* Projects in OpenShifts should be created later today
* Once I get secrets and configMaps, I'll push them there
  * We will also need to create routes
* I need to update jobs in https://github.com/almighty/almighty-jobs/blob/master/devtools-ci-index.yaml#L1128 with path to templates - that will deploy to stage on every build
* When secrets are uploaded to OpenShifts, I can merge https://github.com/openshiftio/saas-launchpad/pull/1 and it should automatically deploy to prod

**Comment by gastaldi** [comment]
@vpavlin this is the template we use right now: https://github.com/openshiftio/launchpad-templates/blob/master/openshift/launchpad-template.yaml 

About the secrets, I'll send you an email instead

**Comment by vpavlin** [comment]
Hmm.. I am afraid our current process will not handle this common template:(. We work on "one template per repo" basis - I've just submitted issues to your 3 repos describing change needed in the templates so that we are able to track the version deployed to prod.

Our current "promote-to-prod" workflow is tied to git commit hashes for versioning - hence the "one template one repo" scheme.

There are 2 solutions - #1 we extend our workflow for this use case - which I cannot do now, and I am not even sure how to do it easily, #2 you update your templates in repositories so that they are up to date with the common template and we use those - I prefer #2:)

**Comment by gastaldi** [comment]
I am fine with #2. I'll review the existing templates and let you know

**Comment by gastaldi** [comment]
As expected. the separate templates are outdated and won't work with our current codebase. 
We need to update the separate templates, which may not be the most enjoyable thing to do :)

**Comment by quintesse** [comment]
That's not going to be trivial. The combined template is not a simple copy & paste of 3 files together. Maintaining them synced is going to be a manual job that's just asking for mistakes.

**Comment by vpavlin** [comment]
Where do you see issues?

**Comment by quintesse** [comment]
@vpavlin in maintaining them synced. For example this is a WiP PR for the combined template: https://github.com/jorgemoralespou/launchpad-templates/commit/1ca6840547eafeb22158300f908008884bc4fe7e . Now imagine having to re-apply that to those 3 other templates again. That will be a manual process because it's not just a simple copy & paste. This will be error-prone meaning that we'll need to test each of the separate templates as well. 

Now maybe these templates don't change much once they are ready, but we have several big(-ish) changes coming up exactly because the current template doesn't follow guidelines.

So in the long run I'd be more inclined to go with option 1 than option 2.

**Comment by jorgemoralespou** [comment]
> We work on "one template per repo" basis.
@vpavlin Are you saying that to deploy launchpad, you need 3 templates, one for backend, on for the frontend and on for Mission Control?

**Comment by gastaldi** [comment]
Given the current situation I'd like to say that I agree with @jorgemoralespou and @quintesse that option 1 would be more interesting. 

I'd be more than happy to help you with the necessary steps to make that happen.

**Comment by vpavlin** [comment]
I understand your PoV. But there are couple issues with option 1

* I am gone for next 2 weeks, so anything that needs change will *probably* have to wait 
* We don't use image streams - reason is that as we don't build in OpenShift, we would have to do 2 steps instead of 1 wrt getting an update there - inform OpenShift about new image + upload new template. We use commit hash as the image tag, so when we (re)deploy a template, we just add commit hash as a param and it updates in one step.
* We don't use pipelines (yet), all the jobs are defined in https://github.com/almighty/almighty-jobs/blob/master/devtools-ci-index.yaml and for you special case we would have to add new pretty complex job/pipeline. If you would have the 3-templates scheme, we are basically ready to go, because you already build there, so it's mostly just about adding a reference to the template in the job definitions.
* There is always some magic, which can be added, but our current workflow is stupid simple - https://github.com/openshiftio/saas#the-process - basically build, deploy, submit PR with a simple change, once approved, your commit runs in prod. Adding more magic is not always best solution - and the effort put into that is, from my pov, not worth it as we plan to switch to pipelines in the future anyway.
* If you look at how things are done in OpenShift.io/fabric8 for it's users, the aim is to generate as much of the templates as possible and that is also done per repo (AFAIK), so I'd rather push you into that direction than otherwise.

btw..the change you shared is pretty confusing - it seems like most of it is just a move of that parameters part up to the top of the file. I'd like to see a different change where you move away from parameters and use configMaps/secrets instead, as that allows for a transparent dev/stage/prod separation. This is also another "blocker" for move to DevTools clusters as we have no way of securely maintaining those parameters for you (we can do that for configMaps and secrets though).

Summary: If you want me to introduce more magic, it will need time - 2+ weeks and I don't have any solution in that direction in my head at the moment. You will need to switch to configMaps/secrets anyway (those can still be templates if that's needed for your use case). I'd prefer if you switched to deployment based on image tags rather than image streams, but that's probably up for discussion, but again, there is no way in our workflow how to work with it atm.

@kbsingh Anything else? Do you have a different point of view?

Hope this helps to understand current situation.

**Comment by quintesse** [comment]
> I'd like to see a different change where you move away from parameters and use configMaps/secrets instead

That's in that change too.

> We don't use image streams

Which is in that change too... unfortunately? But that's what we get told is a better way of doing things: https://github.com/openshiftio/launchpad-templates/issues/15

So it looks more and more that any separate templates could possibly be very different from the combined template. Not really a situation we want to be in IMO.

If forced to use separate templates I would suggest *only* switching to ConfigMap and not apply any other changes even if that goes against recommended practices.

**Comment by jorgemoralespou** [comment]
@vpavlin Let me address what respects to OpenShift. Of course, not going to argue about your tooling.

The template @gastaldi and @quintesse shared has some:
- Reordering to made reading easier
- [ConfigMaps](https://github.com/jorgemoralespou/launchpad-templates/blob/master/openshift/launchpad-template.yaml#L95-L114) to centralize configuration
- [ImageStreams](https://github.com/jorgemoralespou/launchpad-templates/blob/master/openshift/launchpad-template.yaml#L115-L144) as that's the best way to move templates from environment to environment

To my last point, ImageStreams is just an indirection to the actual image. The imageStreams can contain tags to be applied, so there's really no need to use/know the sha256. At deployment time, the DeploymentCOnfig makes sure the SHA256 is injected for the ImageStreamTag used, so that you can then rollover/rollback on your application in a predictive way.

What's the main benefit of ImageStreams, that like with "github commit ids" a sha256 to identify an image is something only a machine can do. That's why in github people use "human readable tags", and that's why in OpenShift we use ImageStreamsTags. Also, an imagestream encapsulates the origin of the image, so that you can deploy software in on-premises environments where images are proxied through capabilities like satellite, nexus or artifactory.

We can discuss what's best practices, but of course, if your tooling is opinionated and can not be easily adjusted, then there's probably no means. 

I would consider that trying to use OpenShift's best practices to build and run software meant for OpenShift is convenient. It's a way for us to keep learning to create the platform and to make software that will use the platform.

**Comment by kbsingh** [comment]
@jorgemoralespou how do imagestreams work for images hosted in different repos ?

**Comment by jorgemoralespou** [comment]
@kbsingh you can:

Have an imagestream follow an specific image and repo. That's what by default "oc import-image" will do.

You can have every tag track a different repo, as in the ImageStream's tag definition, you can point a DockerImage, and specify a different docker URL.

When you manage images coming from different sources, this management is not automatic. But definitely it's easier to manage in a centralized place (the imagestream) than in multiple places (when you use the same image in multiple deployments).

**Comment by vpavlin** [comment]
Originally, we used `:latest` tag in our deployments (which is a terrible practice, I know:) ) with `oc deploy --latest` and potentially `oc apply -f ...`, which brought couple issues, where one them was the chicken-egg problem where we needed to update the image and template at the same time. 

Our solution was to use specific tags with commit hashes and just doing `oc apply -f ...`. We've thought about imageStreams, but could not figure out how to do it in one operation there with remote registry, because afaik you need to do `oc import-image` everytime you push new image and then do `oc apply`. Did we miss something there?

**Comment by jorgemoralespou** [comment]
Proper versioning include version schemas for every artifacts including various tags, e.g:

Version 1.2.3, can be tagged as: v1.2, v1.2.3, v1.2.3.xyz, latest

So you can use any of the tags in the templates or in the imagestreams, they do not need to be complete.

If you look into how JBoss MdW products release, they have and Imagestream that they distribute, with major releases and latest, and can be updated every release, and then they have templates which can reference those tags.

E.g. for openjdk. Imagestream defines 2 tags, 1.0 and 1.1 (https://github.com/jboss-openshift/application-templates/blob/master/jboss-image-streams.json#L780-L820), template uses 1.1. version (https://github.com/jboss-openshift/application-templates/blob/master/openjdk/openjdk18-web-basic-s2i.json#L159) and then if you import the imagestream from the registry:
![image](https://user-images.githubusercontent.com/78350/27829346-76507770-60c1-11e7-9bd6-9f86f9c628d5.png)

And there's some more that were not imported as by default only 5 tags are imported.
````
info: The remote repository contained 3 additional tags which were not imported: 1.0-4, 1.0-3, 1.0-2
````

So that means that even there is new releases on the branches 1.0 and 1.1, my template will always use the latest of that branch.

Then it is a matter of how you want to version launchpad. Do you want to version everything at once, or every component independently?

Hope this helps.

**Comment by ALRubinger** [comment]
Status:  

* Reroute DNS for launch.openshift.io and launch-stage.openshift.io
* New services running at: https://launch.prod-preview.openshift.io/
* Support appdev(-stage).openshift.io

**Comment by gastaldi** [comment]
Production URL:  http://launchpad-nginx-launchpad-production.09b5.dsaas.openshiftapps.com/wizard

**Comment by gastaldi** [comment]
Production: https://launch.openshift.io
Staging: https://launch.prod-preview.openshift.io

**Comment by gastaldi** [comment]
Referenced gitlab issue: https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/429

**Comment by gastaldi** [comment]
The launch-stage.openshift.io domain will be dropped, since IT already have TLS certificates for *.prod-preview.openshift.io and it maintains the standard so it's easier to automate, support, etc...
